# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Scriptor"

# A description of your site for meta tag, search engine results.
description: "this website is a assignment for course 02806 Social data analysis and visualization Spring 23"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: "/bbk-social-data-visual.github.io"

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://bbk-social-data-visual.github.io"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /bbk-social-data-visual.github.io/
  - text: About
    url: /bbk-social-data-visual.github.io/about/
  - text: Style Guide
    url: /bbk-social-data-visual.github.io/style-guide/
  - text: Tags
    url: /bbk-social-data-visual.github.io/tags/

# The shortname for your Disqus site to enable comments.
# disqus: justgoodthemes

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; Scriptor all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
